version: "3.5"

services:
  # Database
  postgres:
    image: postgres:10-alpine
    restart: always
    container_name: postgres
    command: postgres -c log_statement=all
    ports:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:delegated
      - ./postgres/scripts:/docker-entrypoint-initdb.d:delegated
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - bazuki_backend

  # APIs
  test:
    build: ./test
    container_name: test
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./api/.env
    networks:
      - bazuki_backend
    volumes:
      - ./api:/usr/src/app/api:delegated
      - ./coverage:/usr/src/app/coverage:delegated
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bazuki_backend:
    external: true